"""Make user profile fields nullable

Revision ID: 45758687e8f0
Revises: e669ee76d77b
Create Date: 2026-07-19 19:43:24.692476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45758687e8f0'
down_revision: Union[str, Sequence[str], None] = 'e669ee76d77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'education',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'university',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'cgpa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('users', 'career_goal',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'dream_country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'risk_tolerance',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'risk_tolerance',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'dream_country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'career_goal',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'cgpa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('users', 'university',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'education',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
